FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# Install app dependencies
RUN npm install
# RUN npm run migrate
# RUN npm run seed

# If you are building your code for production
# RUN npm ci --omit=dev

# EXPOSE 3000
CMD [ "npm", "run", "dev" ]
