FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Bundle app source
COPY . .

# ARG NEXT_PUBLIC_API_BASE_URL="http://backend:8000"
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}

# Install app dependencies
RUN npm install && npm run build
# If you are building your code for production
# RUN npm ci --omit=dev

# EXPOSE 3000
CMD [ "npm", "run", "start" ]
